[program:artapedia-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artapedia/artisan queue:work database --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/artapedia/storage/logs/queue-worker.log
stopwaitsecs=3600

[program:artapedia-schedule]
command=bash -lc "sleep 50 && exec php /var/www/artapedia/artisan schedule:work"
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/artapedia/storage/logs/schedule-worker.log
